name: workcake
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+59

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # better_selection:
  #   git: https://github.com/letungcntt/better_selection.git
  bitsdojo_window:
    git:
      url: https://github.com/hieplee2997/bitsdojo_window.git
      path: bitsdojo_window
  calendar_view: ^0.0.5
  connectivity_plus: ^2.3.0
  context_menus: ^1.0.1
  cookie_jar: ^3.0.1
  crop_your_image: ^0.7.2
  crypto: ^3.0.2
  cupertino_icons:
  dart_emoji:
  dotted_border:
  device_info_plus: ^3.2.4
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  encrypt: ^5.0.0
  extended_image: ^4.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.3
  file_selector_platform_interface: ^2.0.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_highlighter: ^0.1.1
  flutter_linkify:
    git: https://github.com/hieplee2997/flutter_linkify.git
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^8.1.1+1
  flutter_macos_webview: ^0.0.6
  flutter_markdown:
  flutter_phoenix:
  flutter_portal: ^1.1.1
  flutter_svg: ^1.0.0
  flutter_spinkit: ^5.0.0
  flutter_webrtc:
    git: https://github.com/hieplee2997/flutter-webrtc.git
  flutter_widget_from_html:
    git:
      url: https://github.com/dunm165913/flutter_widget_from_html
      ref: cf65307681c9670979d865f0b7b47f18c8ec2027
  fuzzy: ^0.4.0-nullsafety.0
  get_it: ^6.1.1
  googleapis: ^7.0.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.4
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  html: ^0.15.0
  http: ^0.13.1
  image: ^3.0.7
  intl: ^0.17.0
  isar: 2.2.1
  isar_flutter_libs: 2.2.1
  just_the_tooltip: ^0.0.11+2
  logger: ^1.0.0
  lottie: ^1.3.0
  objectbox: ^1.4.1
  objectbox_flutter_libs: any
  otp_text_field: ^1.1.1
  path_provider: ^2.0.1
  phoenix_wings: ^1.0.2
  phosphor_flutter: ^1.4.0
  platform_device_id: ^1.0.1
  popover:
    git:
      url: https://github.com/duydat09/popover.git
  provider: ^6.0.0
  qr_flutter: ^4.0.0
  record: ^4.1.1
  rxdart:
  scrollable_positioned_list: 0.2.0-nullsafety.0
  sdp_transform: ^0.3.0
  sentry_flutter: ^6.6.3
  shared_preferences: ^2.0.4
  shimmer: ^2.0.0
  simple_tooltip: ^1.0.0
  stacked_services: ^0.8.5
  sticky_headers: ^0.2.0
  syncfusion_flutter_pdfviewer:
  syncfusion_flutter_xlsio: ^20.2.48-beta
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.5
  video_compress: ^3.1.0
  file_picker: ^4.6.0

  vs_scrollbar: ^0.2.0
  xml: ^5.0.0
  process_run: ^0.12.3+2
  audioplayers: ^1.0.1
  local_notifier: ^0.1.5

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  isar_generator: 2.2.1
  objectbox_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/emoji_used/
    - assets/images/emoji_smile/
    - assets/images/emoji_animal/
    - assets/images/emoji_food/
    - assets/images/logo_app/
    - assets/images/logobank/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf

flutter_intl:
  enabled: true