name: workcake
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+59

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 
  provider: ^5.0.0
  intl: ^0.17.0
  get_it: ^6.1.1
  http: ^0.13.1
  html: ^0.15.0
  dio: ^4.0.0
  fluro: ^2.0.3
  shimmer: ^2.0.0
  logger: ^1.0.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.3
  google_fonts: ^2.2.0
  path_provider: ^2.0.1 
  flutter_local_notifications: ^8.1.1+1
  rxdart:
  extended_image: ^4.1.0
  flutter_highlighter: ^0.1.1
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  multi_image_picker: ^4.8.00
  lottie: ^1.0.1
  device_info: ^2.0.0
  encrypt: ^5.0.0
  flutter_linkify:
    git: https://github.com/hieplee2997/flutter_linkify.git
  image: ^3.0.7
  popover: ^0.2.6+3
  simple_tooltip: ^1.0.0

  stacked_services: ^0.8.5
  timeline_tile: ^2.0.0
  bitsdojo_window:
    git:
      url: https://github.com/hieplee2997/bitsdojo_window.git
      path: bitsdojo_window

  flutter_portal: ^0.4.0-nullsafety.0
  flutter_markdown:
  file_selector_platform_interface: ^2.0.0
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.3
  file_picker: ^4.6.0

  scrollable_positioned_list: 0.2.0-nullsafety.0
  otp_text_field: ^1.1.1

  flutter_webrtc:
    git: https://github.com/hieplee2997/flutter-webrtc.git
  sdp_transform: ^0.3.0
  isar: 2.2.1
  isar_flutter_libs: 2.2.1
  phoenix_wings: ^1.0.2
  sticky_headers: ^0.2.0
  flutter_svg: ^0.22.0
  connectivity_plus: ^2.3.0
  phosphor_flutter: ^1.4.0
  better_selection:
    git: https://github.com/letungcntt/better_selection.git
  dart_vlc:
    # git:
    #   url: https://github.com/letungcntt/dart_vlc
  vs_scrollbar: ^0.2.0
  flutter_macos_webview: ^0.0.6
  video_compress: ^3.1.0
  fuzzy: ^0.4.0-nullsafety.0
  crop_your_image: ^0.7.2
  flutter_phoenix: 
  dart_emoji:
  context_menus: ^1.0.1
  googleapis: ^7.0.0
  google_sign_in: ^5.2.4
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  objectbox: ^1.4.1
  objectbox_flutter_libs: any
  uuid: ^3.0.5
  qr_flutter: ^4.0.0
  syncfusion_flutter_pdfviewer:
  ffmpeg_kit_flutter: ^4.5.1
  just_the_tooltip: ^0.0.11+2
  just_audio: ^0.9.21
  record: ^4.1.1
  dotted_border:

dev_dependencies:
  hive_generator: ^1.0.1
  isar_generator: 2.2.1
  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/emoji_used/
    - assets/images/emoji_smile/
    - assets/images/emoji_animal/
    - assets/images/emoji_food/
    - assets/icons/
    - assets/musics/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf

flutter_intl:
  enabled: true